server:
  port: 8080
  servlet:
    context-path: /v1/merchant/rest-api
  tomcat:
    max-threads: 400
eureka:
  client:
    service-Url:
      defaultZone: http://cams-eureka-server-granaderos.apps.us-west-2.online-starter.openshift.com/eureka
spring:
  main:
    allow-bean-definition-overriding: true  
